markdown: kramdown
theme: jekyll-theme-hacker
title: Вадим Ушаков — персональный сайт
permalink: pretty
gems:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
